Stripe/Models/ViewModels/SubscriptionViewModel.cs
namespace Stripe.Models
{
    public class SubscriptionViewModel
    {
        public string Name { get; set; }
        public string Id { get; set; }
        public int Amount { get; set; }
        public string Currency { get; set; }
        public string Status { get; set; }
    }
}

Stripe/Controllers/SubscriptionController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Stripe.Models;
using Stripe.Services;

namespace Stripe.Controllers
{
    public class SubscriptionController : BaseController
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IDonationService _donationService;
        private readonly IOptions<StripeSettings> _stripeSettings;

        public SubscriptionController(UserManager<ApplicationUser> userManager,
            IDonationService donationService,
            IOptions<StripeSettings> stripeSettings)
        {
            _userManager = userManager;
            _donationService = donationService;
            _stripeSettings = stripeSettings;
        }
        public IActionResult Delete(string subscriptionId)
        {
            var subscriptionService = new StripeSubscriptionService(_stripeSettings.Value.SecretKey);
            var result = subscriptionService.Cancel(subscriptionId);

            SetTempMessage($"You have successfully deleted '{result.StripePlan.Name}' subscription");
            return RedirectToAction("Index", "Manage");
        }

    }
}

Stripe/Views/Shared/Components/Subscriptions/View.cshtml
@model Stripe.Models.CustomerPaymentViewModel

<div class="col-lg-12">

    @if (Model.Subscriptions == null || !Model.Subscriptions.Any())
    {
        <h2>There are no subscriptions for now</h2>
    }
    else
    {

        <table class="table table-striped">
            <thead>
            <tr>
                <td>Subscription Name</td>
                <td>Currency</td>
                <td>Amount</td>
                <td>Status</td>
                <td></td>
            </tr>
            </thead>

            <tbody>
            @foreach (var subscription in Model.Subscriptions)
            {
                <tr>
                    <td>@subscription.Name</td>
                    <td>@subscription.Currency</td>
                    <td>@(subscription.Amount / 100)</td>
                    <td>@subscription.Status</td>
                    <td><a class="btn btn-primary" asp-action="Delete" asp-controller="Subscription" asp-route-subscriptionId=@subscription.Id>Delete</a></td>
                </tr>
            }
            </tbody>
        </table>
    }
</div>
<a asp-action="Index" asp-controller="Home" class="btn btn-default">Add New Subscription</a>