Stripe/Models/ViewModels/SubscriptionViewModel.cs
namespace Stripe.Models
{
    public class SubscriptionViewModel
    {
        public string Name { get; set; }
        public string Id { get; set; }
        public int Amount { get; set; }
        public string Currency { get; set; }
        public string Status { get; set; }
    }
}

Stripe/Controllers/BillingController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Stripe.Models;
using Stripe.Services;

namespace Stripe.Controllers
{
    public class BillingController : Controller
    {
        private readonly IDonationService _donationService;
        private readonly UserManager<ApplicationUser> _userManager;

        public BillingController(
            UserManager<ApplicationUser> userManager, 
            IDonationService donationService)
        {
            _userManager = userManager;
            _donationService = donationService;
        }

        public async Task<IActionResult> Payment(int id)
        {
            var user = await GetCurrentUserAsync();
            var payment = new PaymentViewViewModel();
            var donation = _donationService.GetById(id);
            //if(donation.CycleId == )
            //payment.Subscriptions = user.Subscriptions.Select(s => new SubscriptionViewModel()).ToList();


            // Get Card types 

            return View(donation);
        }

        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }
    }
}

Stripe/Controllers/SubscriptionController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Stripe.Models;
using Stripe.Services;

namespace Stripe.Controllers
{
    public class SubscriptionController : BaseController
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IDonationService _donationService;
        private readonly IOptions<StripeSettings> _stripeSettings;

        public SubscriptionController(UserManager<ApplicationUser> userManager,
            IDonationService donationService,
            IOptions<StripeSettings> stripeSettings)
        {
            _userManager = userManager;
            _donationService = donationService;
            _stripeSettings = stripeSettings;
        }
        public IActionResult Delete(string subscriptionId)
        {
            var subscriptionService = new StripeSubscriptionService(_stripeSettings.Value.SecretKey);
            var result = subscriptionService.Cancel(subscriptionId);

            SetTempMessage($"You have successfully deleted '{result.StripePlan.Name}' subscription");
            return RedirectToAction("Index", "Manage");
        }

    }
}

Stripe/Views/Billing/_Subscriptions.cshtml
@model IEnumerable<Subscription>
@if (Model != null && Model.Any())
{
    foreach (var item in Model)
    {
        <div>
            <h3>@Html.DisplayFor(modelItem => item.SubscriptionPlan.Name) - @item.SubscriptionPlan.Currency @item.SubscriptionPlan.Price / @item.SubscriptionPlan.Interval</h3>

            @if (item.IsTrialing() && item.End == null)
            {
                <p><strong>Free Trial Until @item.TrialEnd.Value.ToString("MMMM dd, yyyy")</strong></p>
            }
            @if (item.End == null)
            {
                <p>
                    <a href="@Url.Action("CancelSubscription", "Billing", new {id = item.Id})">Cancel Subscription</a> - @Html.ActionLink("Change Plan", "ChangeSubscription", "Billing")
                </p>
            }
            else
            {
                <p>Your Subscription will not be renewed after @item.End.Value.ToString("MMMM dd, yyyy")</p>
                <p><a href="@Url.Action("ReActivateSubscription")" class="btn btn-primary">Re-Activate Subscription</a></p>
            }
        </div>
    }
}
else
{
    <h3>You don't have any subscription</h3>
    <a href="@Url.Action("DeleteAccount")" id="delete-account">Delete Account</a>
}