Stripe/Models/Donation.cs
using System;

namespace Stripe.Models
{
    public class Donation
    {
        public int Id { get; set; }

        public string CycleId { get; set; }

        public int? DonationAmount { get; set; }

        public string UserId { get; set; }

        public virtual ApplicationUser User { get; set; }

        public DateTime? TransactionDate { get; set; }

        public int SelectedAmount { get; set; }

        public string currency { get; set; }
    }
}

Stripe/Models/ViewModels/DonationViewModel.cs
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stripe.Services;

namespace Stripe.Models
{
    public class DonationViewModel
    {
        public int Id { get; set; }

        public string CycleId { get; set; }

        public int? DonationAmount { get; set; }

        public List<SelectListItem> DonationCycles { get; set; }

        public int SelectedAmount { set; get; }

        public List<DonationListOption> DonationOptions { get; set; }

        private const int StripeMultiplier = 100;

        public string PaymentGatway { get; set; }


        public DonationViewModel()
        {
        }

        public DonationViewModel(List<DonationListOption> donationOptions)
        {
            DonationOptions = donationOptions;
        }

        public int GetAmount()
        {
            if (DonationAmount > 0)
                return DonationAmount.Value * StripeMultiplier;

            if (SelectedAmount > 0)
                return DonationOptions[SelectedAmount - 1].Amount * StripeMultiplier;

            return 0;
        }

        public string GetCycle()
        {
            var pc = EnumInfo<PaymentCycle>.GetValue(this.CycleId);
            return EnumInfo<PaymentCycle>.GetDescription(pc);
        }

        public int GetDisplayAmount()
        {
            if (DonationAmount > 0)
                return DonationAmount.Value;

            if (SelectedAmount > 0)
                return DonationOptions[SelectedAmount - 1].Amount;

            return 0;
        }

        public string GetFullDescription()
        {
            return $"{DonationOptions[SelectedAmount - 1].Amount} {DonationOptions[SelectedAmount - 1].Reason}";
        }

        public string GetDescription()
        {
            return DonationOptions[SelectedAmount - 1].Reason;
        }

        public static implicit operator DonationViewModel(Donation donation)
        {
            return new DonationViewModel(new List<DonationListOption>())
            {
                Id = donation.Id,
                CycleId = donation.CycleId,
                DonationAmount = donation.DonationAmount,
                SelectedAmount = donation.SelectedAmount,
            };
        }
    }
}

Stripe/Controllers/DonationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Stripe.Models;
using Stripe.Services;

namespace Stripe.Controllers
{
    [Authorize]
    public class DonationController : Controller
    {
        private const string DonationCaption = "Renewal Center donation";
        private readonly IDonationService _donationService;
        private readonly IOptions<StripeSettings> _stripeSettings;
        private readonly UserManager<ApplicationUser> _userManager;

        public DonationController(
            UserManager<ApplicationUser> userManager,
            IDonationService donationService,
            IOptions<StripeSettings> stripeSettings)
        {
            _userManager = userManager;
            _donationService = donationService;
            _stripeSettings = stripeSettings;
        }

        [Route("Donation/Payment")]
        [HttpGet]
        public ActionResult payment()
        {
            return RedirectToAction("index", "home");
        }

        [Route("Donation/Payment/{id}")]
        public async Task<IActionResult> Payment(int id)
        {
            var user = await GetCurrentUserAsync();
            var donation = _donationService.GetById(id);
            var detail = (DonationViewModel)donation;
            detail.DonationOptions = _donationService.DonationOptions;

            // Check for existing customer
            // edit = 1 means user wants to edit the credit card information
            if (!string.IsNullOrEmpty(user.StripeCustomerId))
            {
                try
                {
                    var CustomerService = new StripeCustomerService(_stripeSettings.Value.SecretKey);
                    StripeCustomer objStripeCustomer = CustomerService.Get(user.StripeCustomerId);
                    StripeCard objStripeCard = null;

                    if (objStripeCustomer.Sources != null && objStripeCustomer.Sources.TotalCount > 0 && objStripeCustomer.Sources.Data.Any())
                    {
                        objStripeCard = objStripeCustomer.Sources.Data.FirstOrDefault().Card;
                    }

                    if (objStripeCard != null && !string.IsNullOrEmpty(objStripeCard.Id))
                    {
                        var objCustomerRePaymentViewModel = new CustomerRePaymentViewModel
                        {
                            Name = user.FullName,
                            AddressLine1 = user.AddressLine1,
                            AddressLine2 = user.AddressLine2,
                            City = user.City,
                            State = user.State,
                            Country = user.Country,
                            Zip = user.Zip,
                            DonationId = donation.Id,
                            Description = detail.GetDescription(),
                            Frequency = detail.GetCycle(),
                            Amount = detail.GetDisplayAmount(),
                            Last4Digit = objStripeCard.Last4,
                            CardId = objStripeCard.Id,
                            Currency = (objStripeCustomer.Currency + "").ToUpper(),
                            DisableCurrencySelection = string.IsNullOrEmpty(objStripeCustomer.Currency) ? "0" : "1"

                        };

                        return View("RePayment", objCustomerRePaymentViewModel);
                    }
                }
                catch (StripeException sex)
                {
                    ModelState.AddModelError("CustomerNotFound", sex.Message);
                }
            }

            var model = new CustomerPaymentViewModel
            {
                Name = user.FullName,
                AddressLine1 = user.AddressLine1,
                AddressLine2 = user.AddressLine2,
                City = user.City,
                State = user.State,
                Country = string.IsNullOrEmpty(user.Country) ? "US" : user.Country,
                Zip = user.Zip,
                DonationId = donation.Id,
                Description = detail.GetDescription(),
                Frequency = detail.GetCycle(),
                Amount = detail.GetDisplayAmount(),
                Currency = "USD"
            };

            return View("Payment", model);
        }

        [HttpPost]
        public async Task<IActionResult> Payment(CustomerPaymentViewModel payment)
        {
            try
            {
                var user = await GetCurrentUserAsync();

                if (!ModelState.IsValid)
                {
                    return View(payment);
                }

                var customerService = new StripeCustomerService(_stripeSettings.Value.SecretKey);
                var donation = _donationService.GetById(payment.DonationId);

                // Construct payment
                if (string.IsNullOrEmpty(user.StripeCustomerId))
                {
                    var customer = new StripeCustomerCreateOptions
                    {
                        Email = user.Email,
                        Description = $"{user.Email} {user.Id}",
                        SourceCard = new SourceCard
                        {
                            Name = payment.Name,
                            Number = payment.CardNumber,
                            Cvc = payment.Cvc,
                            ExpirationMonth = payment.ExpiryMonth,
                            ExpirationYear = payment.ExpiryYear,
                            StatementDescriptor = _stripeSettings.Value.StatementDescriptor,
                            Description = DonationCaption,
                            AddressLine1 = payment.AddressLine1,
                            AddressLine2 = payment.AddressLine2,
                            AddressCity = payment.City,
                            AddressState = payment.State,
                            AddressCountry = payment.Country,
                            AddressZip = payment.Zip
                        }
                    };
                    var stripeCustomer = customerService.Create(customer);
                    user.StripeCustomerId = stripeCustomer.Id;
                }
                else
                {
                    //Check for existing credit card, if new credit card number is same as exiting credit card then we delete the existing
                    //Credit card information so new card gets generated automatically as default card.
                    try
                    {
                        var ExistingCustomer = customerService.Get(user.StripeCustomerId);
                        if (ExistingCustomer.Sources != null && ExistingCustomer.Sources.TotalCount > 0 && ExistingCustomer.Sources.Data.Any())
                        {
                            var cardService = new StripeCardService(_stripeSettings.Value.SecretKey);
                            foreach (var cardSource in ExistingCustomer.Sources.Data)
                            {
                                cardService.Delete(user.StripeCustomerId, cardSource.Card.Id);
                            }
                        }
                    }
                    catch (Exception exSub)
                    {
                    }

                    var customer = new StripeCustomerUpdateOptions
                    {
                        SourceCard = new SourceCard
                        {
                            Name = payment.Name,
                            Number = payment.CardNumber,
                            Cvc = payment.Cvc,
                            ExpirationMonth = payment.ExpiryMonth,
                            ExpirationYear = payment.ExpiryYear,
                            StatementDescriptor = _stripeSettings.Value.StatementDescriptor,
                            Description = DonationCaption,
                            AddressLine1 = payment.AddressLine1,
                            AddressLine2 = payment.AddressLine2,
                            AddressCity = payment.City,
                            AddressState = payment.State,
                            AddressCountry = payment.Country,
                            AddressZip = payment.Zip
                        }
                    };

                    var stripeCustomer = customerService.Update(user.StripeCustomerId, customer);
                    user.StripeCustomerId = stripeCustomer.Id;
                }

                user.FullName = payment.Name;
                user.AddressLine1 = payment.AddressLine1;
                user.AddressLine2 = payment.AddressLine2;
                user.City = payment.City;
                user.State = payment.State;
                user.Country = payment.Country;
                user.Zip = payment.Zip;
                await _userManager.UpdateAsync(user);


                // Add customer to Stripe
                if (EnumInfo<PaymentCycle>.GetValue(donation.CycleId) == PaymentCycle.OneOff)
                {
                    var model = (DonationViewModel)donation;
                    model.DonationOptions = _donationService.DonationOptions;

                    var charges = new StripeChargeService(_stripeSettings.Value.SecretKey);

                    // Charge the customer
                    var charge = charges.Create(new StripeChargeCreateOptions
                    {
                        Amount = model.GetAmount(),
                        Description = DonationCaption,
                        Currency = payment.Currency.ToLower(),
                        CustomerId = user.StripeCustomerId,
                        //ReceiptEmail = user.Email,
                        StatementDescriptor = _stripeSettings.Value.StatementDescriptor,
                    });

                    if (charge.Paid)
                    {

Stripe/Views/Donation/CreditCard.cshtml
@using Stripe.Controllers
@model Stripe.Models.CustomerPaymentViewModel

@{
    ViewBag.Title = "Credit Card";
}

<div class="container">
    <form asp-action="CreditCard" asp-controller="Donation" method="POST" class="form-horizontal" role="form">
        <fieldset>
            <legend>Donation</legend>
            
            <input hidden asp-for="DonationId"/>

            <div class="form-group">
                <label class="col-sm-3 control-label" for="card-holder-name">Name on Card</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" asp-for="Name" placeholder="Card Holder's Name">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label" for="card-number">Card Number</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" asp-for="CardNumber" placeholder="Debit/Credit Card Number">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label" for="expiry-month">Expiration Date</label>
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-xs-3">
                            <select class="form-control col-sm-2" asp-for="ExpiryMonth">
                                <option>Month</option>
                                <option value="01">Jan (01)</option>
                                <option value="02">Feb (02)</option>
                                <option value="03">Mar (03)</option>
                                <option value="04">Apr (04)</option>
                                <option value="05">May (05)</option>
                                <option value="06">June (06)</option>
                                <option value="07">July (07)</option>
                                <option value="08">Aug (08)</option>
                                <option value="09">Sep (09)</option>
                                <option value="10">Oct (10)</option>
                                <option value="11">Nov (11)</option>
                                <option value="12">Dec (12)</option>
                            </select>
                        </div>
                        <div class="col-xs-3">
                            <select class="form-control" asp-for="ExpiryYear">
                                <option value="17">2017</option>
                                <option value="18">2018</option>
                                <option value="19">2019</option>
                                <option value="20">2020</option>
                                <option value="21">2021</option>
                                <option value="22">2022</option>
                                <option value="23">2023</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label" for="cvc">Card CVV</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" asp-for="Cvc" placeholder="CVC">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                    <button class="btn btn-success" type="submit">Submit Payment</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>